### ISSUE TITLE
Pull analysis VM's IP address from XenServer

### ISSUE THREAD

**Issue by tklengyel** [kill-9-me/Cuckoo-Xenserver#2]
I think this would be a nice addition if you have XenTools installed in the analysis VM. No need to manually configure the IP. It should be accessible as xe vm-list params=name-label,networks does tell you this info:

```
# xe vm-list params=name-label,networks
name-label ( RW)    : win-xp-sp3-base
      networks (MRO): 0/ip: 10.0.0.68

name-label ( RW)    : win-xp-sp3-intel1
      networks (MRO): 0/ip: 10.0.0.70
```

**Comment by kill-9-me** [comment]
I would recommend against it. The reason for this is most malware checks for the existence of virtualization tools. (VMWare tools, Xen Tools, Virtualbox Guest Extensions).

Due to this I won't have it automatically try and snag the IP.

**Comment by tklengyel** [comment]
@kill-9-me: that's generally a problem with Cuckoo's in-guest agent as well. So in this case, not installing xentools only marginally increases stealth, if at all.
